### ISSUE TITLE
Problems with .appveyor.yml.example-full

### ISSUE THREAD

**Issue by MarkRivers** [epics-base/ci-scripts#38]
There seem to be several problems with the .appveyor.yml.example-full example.

- It contains two install: sections, lines 19 and 116. appveyor throws an error when it finds the second one.
- I commented out the first one and moved this line into the second install: section:
 ```
 - cinst re2c
```
That allowed base to build.  However, when building sncseq 2.2.8 I got this error:
```pv.c
   Creating library pv.lib and object pv.exp
Generating code
Finished generating code
lemon.c
Generating code
Finished generating code
2 parsing conflicts.
process_begin: CreateProcess(NULL, re2c.exe -s -b -o lexer.c ../snl.re, ...) failed.
make (e=2): The system cannot find the file specified.
seq_main.c
seq_task.c
seq_ca.c
seq_if.c
seq_mac.c
process_begin: CreateProcess(NULL, re2c.exe -s -b -o lexer.c ../snl.re, ...) failed.
make (e=2): The system cannot find the file specified.
make[3]: *** No rule to make target 'lexer.c', needed by 'lexer.obj'.  Stop.
make[3]: *** Waiting for unfinished jobs....
seq_prog.c
make[2]: *** [C:/Users/appveyor/.cache/base-7.0/configure/RULES_ARCHS:58: install.win32-x86] Error 2
make[1]: *** [C:/Users/appveyor/.cache/base-7.0/configure/RULES_DIRS:85: snc.install] Error 2
make[1]: *** Waiting for unfinished jobs....
seq_qry.c
seq_cmd.c
seq_queue.c
   Creating library seq.lib and object seq.exp
Generating code
Finished generating code
make: *** [C:/Users/appveyor/.cache/base-7.0/configure/RULES_DIRS:85: src.install] Error 2
Command exited with code 2
```
It seems like re2c has not been installed.  Is this a problem with the order of things?

- In a previous build I got this error when building mingw
```
Build started
git config --global core.autocrlf true
git clone -q --depth=50 --branch=master https://github.com/epics-modules/asyn.git C:\projects\asyn
git checkout -qf da9ac6d40333a30b57b54a8949d7495b66928df0
Running Install scripts
git submodule update --init --recursive
Submodule '.ci' (https://github.com/epics-base/ci-scripts) registered for path '.ci'
Cloning into 'C:/projects/asyn/.ci'...
Submodule path '.ci': checked out 'a39346bc78b469f3ccc18ab7ad7cdce837d72a05'
cd .ci
git checkout v2.3.4
Previous HEAD position was a39346b Readme: add references, FAQ, Travis badge
HEAD is now at 98bc1d8 Readme: add links to lower level readme pages, fix badge URL
cd ..
python .ci/appveyor/do.py prepare
AppVeyor Build Worker Image: Visual Studio 2015
Python setup
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
PYTHONPATH
  C:\projects\asyn\.ci\appveyor
  C:\windows\SYSTEM32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
platform = win32
Available Visual Studio versions
Found vs2008 in C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat
Found vs2015 in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
Found vs2012 in C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat
Found vs2013 in C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
Found vs2010 in C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat
Loading setup files
Loading setup file .ci\defaults.set
Checking/cloning dependencies
Traceback (most recent call last):
  File ".ci/appveyor/do.py", line 635, in <module>
    main(sys.argv[1:])
  File ".ci/appveyor/do.py", line 632, in main
    args.func(args)
  File ".ci/appveyor/do.py", line 459, in prepare
    [add_dependency(mod) for mod in modlist()]
  File ".ci/appveyor/do.py", line 289, in add_dependency
    .format(ANSI_RED, tag, dep, setup[dep+'_REPOURL'], ANSI_RESET))
RuntimeError: master is neither a tag nor a branch name for BASE (https://github.com/epics-base/epics-base.git)
Command exited with code 1
Get-ChildItem *.tap -Recurse -Force | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
python .ci/appveyor/do.py build test-results -s
Traceback (most recent call last):
  File ".ci/appveyor/do.py", line 635, in <module>
    main(sys.argv[1:])
  File ".ci/appveyor/do.py", line 632, in main
    args.func(args)
  File ".ci/appveyor/do.py", line 536, in build
    setup_for_build(args)
  File ".ci/appveyor/do.py", line 402, in setup_for_build
    with open(os.path.join(cachedir, 'RELEASE.local'), 'r') as f:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\appveyor\\.cache\\RELEASE.local'
Command exited with code 1
```
Is this because neither SET nor BASE is defined for the mingw builds in the .appveyor.yml.example-full file?

**Comment by ralphlange** [comment]
I rearranged the order of things a bit and tried to match it as far as possible to the Travis-CI configuration setup.

The phases `install`, `build_script`, `test_script` and `on_finish` are executed in this order. You're free to distribute everything that needs to be done onto those phases.

The new layout of the example (today in [my fork](https://github.com/ralphlange/ci-scripts), some time later in the main repo) is installing additional stuff at the top of the file
```
install:
# fetch submodules (like ci-scripts)
  - cmd: git submodule update --init --recursive
# for the sequencer
  - cinst re2c
```
and puts the `prepare`, `build` and `test` below the matrix definition:
```
build_script:
  - cmd: python .ci/appveyor/do.py prepare
  - cmd: python .ci/appveyor/do.py build

test_script:
  - cmd: python .ci/appveyor/do.py test
```

But you could also just put the installation of `re2c` above the `prepare` step that builds the prerequisites - including the sequencer if configured that needs `re2c`.

Not defining a version for `BASE` at all (neither in the `.appveyor.yml` configuration nor through a setup file) will have the scripts fall back to using a branch called `master`, which in the case of the Base repository does not exist.

**Comment by MarkRivers** [comment]
Following @ralphlange suggestions above I was able to fix the asyn .appveyor.yml file to build OK.

It seems to be succeeding on the unit tests with static builds but failing 4 out of 54 tests with dynamic builds.  Need to track that down.
