### ISSUE TITLE
Test failure on windows

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/ci-scripts#85]
This appears to be separate from #84.

```
...
======================================================================
ERROR: test_AddMsiTo314 (__main__.TestAddDependencyOptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\ci-scripts\ci-scripts\cue-test.py", line 307, in test_AddMsiTo314
    cue.add_dependency('BASE')
  File "D:\a\ci-scripts\ci-scripts\cue.py", line 602, in add_dependency
    sp.check_call(['patch', '-p1', '-i', os.path.join(ci['scriptsdir'], 'add-msi-to-314.patch')],
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['patch', '-p1', '-i', 'D:\\a\\ci-scripts\\ci-scripts\\add-msi-to-314.patch']' returned non-zero exit status 2.

======================================================================
ERROR: test_patchfile (__main__.TestHooks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\ci-scripts\ci-scripts\cue-test.py", line 871, in test_patchfile
    cue.apply_patch(hook, cwd=self.location)
  File "D:\a\ci-scripts\ci-scripts\cue.py", line 486, in apply_patch
    sp.check_call(['patch', '-p1', '-i', file], cwd=place)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['patch', '-p1', '-i', 'D:\\a\\ci-scripts\\ci-scripts\\test.patch']' returned non-zero exit status 2.
...
```

**Comment by mdavidsaver** [comment]
I have not seen this error in over a year, so I guess it was fixed by someone at some point?
